version: 2.1

commands:
  setup:
    steps:
      - checkout
      - run: emacs --version
  install:
    steps:
      - run: make install
  lint:
    steps:
      - run: make lint

jobs:
  lint:
    docker:
      - image: silex/emacs:26-dev
    steps:
      - setup
      - install
      - lint

workflows:
  version: 2
  default:
    jobs:
      - lint
